{% set name = "python-io-wrapper" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3391787ff0d9870e739294c6392437915502153e695a017450aa46b6d091762

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - io_wrapper
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/davidmegginson/python-io-wrapper
  summary: 'Python3 wrapper to add missing io.RawIOBase methods to a file-like object'
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  license_file: UNLICENSE.md
  doc_url: https://github.com/davidmegginson/python-io-wrapper
  dev_url: https://github.com/davidmegginson/python-io-wrapper

extra:
  recipe-maintainers:
    - kynan
